import type { BackofficeUser } from '@src/types/user.types'

export const usersMock: BackofficeUser[] = [
    {
        id: 1,
        firstName: 'Marie',
        lastName: 'Dupont',
        email: 'marie.dupont@cookus.app',
        thumbnail: null,
        role: 'client',
        createdAt: '2026-01-12T10:00:00Z',
        updatedAt: '2026-01-12T10:00:00Z',
        deletedAt: null,
        cookProfile: null,
    },
    {
        id: 2,
        firstName: 'Luca',
        lastName: 'Bianchi',
        email: 'luca.bianchi@cookus.app',
        thumbnail: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&h=120&fit=crop',
        role: 'cook',
        createdAt: '2026-01-20T15:45:00Z',
        updatedAt: '2026-02-01T08:00:00Z',
        deletedAt: null,
        cookProfile: {
            description: "Chef spécialisé en cuisine italienne avec 10 ans d'expérience dans des restaurants étoilés à Milan et Lyon.",
            speciality: 'italien',
            hourlyRate: '45',
            city: 'Lyon',
        },
    },
    {
        id: 3,
        firstName: 'Aïcha',
        lastName: 'Martin',
        email: 'aicha.martin@cookus.app',
        thumbnail: null,
        role: 'cook',
        createdAt: '2026-02-01T09:20:00Z',
        updatedAt: '2026-02-01T09:20:00Z',
        deletedAt: null,
        cookProfile: {
            description: 'Cuisinière passionnée par les épices et la gastronomie indienne, propose des menus végétariens et végans sur demande.',
            speciality: 'indian',
            hourlyRate: '52',
            city: 'Paris',
        },
    },
    {
        id: 4,
        firstName: 'Admin',
        lastName: 'Cookus',
        email: 'admin@cookus.app',
        thumbnail: null,
        role: 'admin',
        createdAt: '2025-12-15T08:00:00Z',
        updatedAt: '2025-12-15T08:00:00Z',
        deletedAt: null,
        cookProfile: null,
    },
    {
        id: 5,
        firstName: 'Nora',
        lastName: 'Petit',
        email: 'nora.petit@cookus.app',
        thumbnail: null,
        role: 'client',
        createdAt: '2026-02-14T13:30:00Z',
        updatedAt: '2026-02-14T13:30:00Z',
        deletedAt: '2026-02-28T18:10:00Z',
        cookProfile: null,
    },
    {
        id: 6,
        firstName: 'Thomas',
        lastName: 'Leroy',
        email: 'thomas.leroy@cookus.app',
        thumbnail: null,
        role: 'cook',
        createdAt: '2026-02-20T11:00:00Z',
        updatedAt: '2026-02-20T11:00:00Z',
        deletedAt: null,
        cookProfile: {
            description: 'Cuisinier français formé à Lyon, spécialisé dans la cuisine traditionnelle et les plats mijotés.',
            speciality: 'french',
            hourlyRate: '38',
            city: 'Bordeaux',
        },
    },
]
